/**
 * WARNING: EXTREMELY SENSITIVE FILE
 *
 * This file contains critical functions for interacting with Firestore.
 * Any modifications to this file could result in PERMANENT DATA LOSS.
 *
 * DO NOT EDIT THIS FILE UNLESS YOU ARE ABSOLUTELY CERTAIN OF WHAT YOU ARE DOING.
 *
 * Before making any changes:
 * 1. BACK UP YOUR PRODUCTION FIREBASE DATA.
 * 2. Thoroughly test all changes in a development environment.
 * 3. Understand the difference between `updateDoc` and `setDoc`. `setDoc` WILL OVERWRITE documents.
 */

import { doc, getDoc, updateDoc } from 'firebase/firestore';
import { db } from './config';
import { Alert } from 'react-native';

const USER_PROFILE_DOC_REF = doc(db, "rentaData", "userProfile");

/**
 * Updates the 'locations' array in the userProfile document.
 * This function is designed to be safe and will not overwrite other fields.
 *
 * @param {any[]} locations - The new array of locations.
 */
export const updateUserLocations = async (locations: any[]) => {
    try {
        await updateDoc(USER_PROFILE_DOC_REF, {
            locations: locations
        });
    } catch (error) {
        console.error("CRITICAL: Failed to update user locations.", error);
        Alert.alert("Error", "Failed to save changes. Please try again.");
    }
};

/**
 * Retrieves the entire user profile document.
 *
 * @returns {Promise<any | null>} - The user profile data or null if it doesn't exist.
 */
export const getUserProfile = async (): Promise<any | null> => {
    try {
        const docSnap = await getDoc(USER_PROFILE_DOC_REF);
        if (docSnap.exists()) {
            return docSnap.data();
        } else {
            console.warn("User profile document does not exist.");
            return null;
        }
    } catch (error) {
        console.error("CRITICAL: Failed to get user profile.", error);
        Alert.alert("Error", "Failed to load user data. Please try again.");
        return null;
    }
};